import {StyleSheet, Text, View, Dimensions, SafeAreaView} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default styles = StyleSheet.create({
  SettingStayle: {
    fontWeight: '600',
    fontSize: windowWidth * 0.08,
    marginLeft: windowWidth * 0.03,
    marginTop: windowWidth * 0.03,
    color: 'blue',
  },
  Kayarimagee: {
    width: windowWidth * 0.15,
    height: windowWidth * 0.15,
    marginLeft: windowWidth * 0.03,
    marginTop: windowWidth * 0.02,
  },
  ustsolimage1: {
    marginRight: windowWidth * 0.06,
    width: windowWidth * 0.1,
    height: windowWidth * 0.1,
    marginLeft: windowWidth * 0.03,
    marginTop: windowWidth * 0.04,
  },
  ustsolimage: {
    marginRight: windowWidth * 0.05,
    width: windowWidth * 0.07,
    height: windowWidth * 0.07,
    marginLeft: windowWidth * 0.03,
    marginTop: windowWidth * 0.04,
  },
  textName: {
    fontSize: windowWidth * 0.05,
    fontWeight: '600',
    marginTop: windowWidth * 0.05,
    marginLeft: windowWidth * 0.02,
  },
  ButtonView: {
    backgroundColor: 'white',
    width: windowWidth * 0.92,
    height: windowWidth * 0.17,
    marginLeft: windowWidth * 0.04,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  ModalViev: {
    marginTop: windowWidth * 1,
    alignItems: 'center',
    borderRadius: windowWidth * 0.1,
    width: windowWidth * 1,
    height: windowWidth * 0.9,
    backgroundColor: 'white',
  },
  ModalTitleText: {
    fontSize: windowWidth * 0.06,
    fontWeight: '700',
    color: 'blue',
    marginTop: windowWidth * 0.1,
  },
  ModalText: {
    borderWidth:windowWidth*0.005,
    width: windowWidth * 0.8,
    height: windowWidth * 0.12,
    backgroundColor: '#dddddd',
    borderRadius: windowWidth * 0.1,
  },
  ModalText1: {
    fontSize: windowWidth * 0.05,
    marginLeft: windowWidth * 0.05,
    marginTop: windowWidth * 0.025,
  },
  PaswordViev: {
    borderWidth:windowWidth*0.005,
    borderRadius: windowWidth * 0.1,
    width: windowWidth * 0.8,
    height: windowWidth * 0.12,
    marginTop: windowWidth * 0.01,
    backgroundColor: '#dddddd',
  },
  AltMav: {
    alignItems: 'center',
    width: windowWidth * 0.8,
    height: windowWidth * 0.12,
    backgroundColor: 'blue',
    borderRadius: windowHeight * 0.1,
    marginTop: windowHeight * 0.02,
  },
  AltMavTex: {
    fontSize: windowWidth * 0.05,
    color: 'white',
    marginTop: windowWidth * 0.03,
  },
  AnaSayfaAlt: {
    marginTop: windowWidth * 0.05,
    backgroundColor: '#9CDCFE',
    width: windowWidth * 0.9,
    height: windowWidth * 0.4,
    marginLeft: windowWidth * 0.05,
    borderRadius: windowWidth * 0.1,
  },
  AnaSayfaAlt2: {
    marginTop: windowWidth * 0.2,
    color: 'blue',
    fontWeight: '800',
  },
});
