import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  UstView: {
    justifyContent: 'space-between',
    borderRadius: windowWidth * 0.1,
    marginLeft: windowWidth * 0.05,
    width: windowWidth * 0.9,
    height: windowWidth * 0.1,
    backgroundColor: 'black',
    flexDirection: 'row',
  },
  backView: {
    marginRight: windowWidth * 0.02,
    width: windowWidth * 0.08,
    height: windowWidth * 0.08,
    tintColor: 'white',
  },
  ProductText: {
    color: 'white',
    fontSize: windowWidth * 0.06,
  },
  Zoomimage: {
    marginRight: windowWidth * 0.02,
    width: windowWidth * 0.08,
    height: windowWidth * 0.08,
    tintColor: 'white',
  },
  Cartimage: {
    marginRight: windowWidth * 0.02,
    width: windowWidth * 0.08,
    height: windowWidth * 0.08,
    tintColor: 'white',
  },
  DataViev: {
    width: windowWidth * 0.94,
    borderRadius: windowWidth * 0.5,
    marginLeft: windowWidth * 0.05,
  },
  Dataimage: {
    width: windowWidth * 0.9,
    height: windowWidth * 0.5,
    borderRadius: windowWidth * 0.1,
  },
  DuzenView: {
    justifyContent: 'center',
    flexDirection: 'row',
  },
  NikeViev: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: windowWidth * 0.05,
  },
  NikeText: {color: 'white', marginRight: windowWidth * 0.03},
  Onsale: {color: '#50c878'},
  DataTitle: {
    color: 'white',
    fontSize: windowWidth * 0.06,
    fontWeight: '800',
  },
  AedView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: windowWidth * 0.05,
  },
  AedText: {
    color: '#B0E0E6',
    marginTop: windowWidth * 0.04,
    fontSize: windowWidth * 0.04,
  },
  WasAedText: {
    marginLeft: windowWidth * 0.03,
    color: '#808080',
    marginTop: windowWidth * 0.04,
    fontSize: windowWidth * 0.03,
  },
  AltEuView: {
    flexDirection: 'row',
    marginLeft: windowWidth * 0.03,
    marginTop: windowWidth * 0.1,
  },
  Removeimage: {
    width: windowWidth * 0.06,
    height: windowWidth * 0.01,
    tintColor: 'white',
  },
  EuText: {color: 'white', marginLeft: windowWidth * 0.05},
  BedenView: {flexDirection: 'row', marginTop: windowWidth * 0.05},
  BedenAltView: {
    flexDirection: 'row',
    marginLeft: windowWidth * 0.05,
    marginTop: windowWidth * 0.03,
  },
  AyakRenk: {
    flexDirection: 'row',
    marginLeft: windowWidth * 0.05,
    marginTop: windowWidth * 0.03,
  },
  AltTouchableButton: {
    marginLeft: windowWidth * 0.05,
    marginTop: windowWidth * 0.1,
  },
  AzaltViev: {
    marginRight: windowWidth * 0.05,
    justifyContent: 'center',
    alignItems: 'center',
    width: windowWidth * 0.1,
    height: windowWidth * 0.1,
    backgroundColor: 'white',
    borderRadius: windowWidth * 0.05,
  },
  AzaltText: {
    fontSize: windowWidth * 0.1,
    marginBottom: windowWidth * 0.035,
  },
  DegerText: {
    color: 'white',
    fontSize: windowWidth * 0.07,
    fontWeight: '500',
  },
  ArttirButton: {
    borderWidth: windowWidth * 0.005,
    borderColor: 'white',
    marginLeft: windowWidth * 0.05,
    justifyContent: 'center',
    alignItems: 'center',
    width: windowWidth * 0.1,
    height: windowWidth * 0.1,
    borderRadius: windowWidth * 0.05,
  },
  arttirText: {
    color: 'white',
    fontSize: windowWidth * 0.05,
  },
  AddToCardView:{
    borderWidth: windowWidth * 0.005,
    borderColor: 'white',
    marginLeft: windowWidth * 0.05,
    justifyContent: 'center',
    alignItems: 'center',
    width: windowWidth * 0.3,
    height: windowWidth * 0.1,
    borderRadius: windowWidth * 0.05,
  },
  AddToCardText:{
    color: 'white',
    fontSize: windowWidth * 0.0,
  },
  ModalVieew:{
    position: 'absolute',
    bottom: 0,
    marginTop: windowWidth * 0.1,
    width: windowWidth * 1,
    height: windowWidth * 0.5,
    backgroundColor: '#808080',
    borderTopLeftRadius: windowWidth * 0.1,
    borderTopRightRadius: windowWidth * 0.1,
  },
  Modalimaghe:{
    marginTop: windowWidth * 0.05,
    marginLeft: windowWidth * 0.05,
    width: windowWidth * 0.08,
    height: windowWidth * 0.08,
    tintColor: 'black',
  },
  Modalimaghe2:{
    marginTop: windowWidth * 0.05,
    marginLeft: windowWidth * 0.05,
    width: windowWidth * 0.2,
    height: windowWidth * 0.2,
  },
  AyakkabiName:{
    color: 'black',
    fontSize: windowWidth * 0.05,
    marginLeft: windowWidth * 0.03,
    marginTop: windowWidth * 0.05,
  },
  AyakkabiNameView:{
    marginTop: windowWidth * 0.05,
    flexDirection: 'row',
    marginLeft: windowWidth * 0.2,
  },
  TouchableOpahsiteViev:{
    alignItems: 'center',
    justifyContent: 'center',
    width: windowWidth * 0.1,
    height: windowWidth * 0.1,
    backgroundColor: 'white',
    borderRadius: windowWidth * 0.05,
  },
  TouchableOpasiteText:{
    fontSize: windowWidth * 0.1,
    marginBottom: windowWidth * 0.035,
    color: 'black',
  },
  UrunText:{
    color: 'black',
    fontSize: windowWidth * 0.1,
  },
  UrunArttir:{
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    width: windowWidth * 0.1,
    height: windowWidth * 0.1,
    borderRadius: windowWidth * 0.05,
  },
  UrunArttirText:{
    color: 'black',
    fontSize: windowWidth * 0.05,
  },
  FiyatView:{
    marginLeft: windowWidth * 0.5,
    color: 'black',
    fontSize: windowWidth * 0.06,
  },
});
